language: ruby
sudo: false

notifications:
  email: false

rvm:
  - 2.5.1

env:
 - "RAILS_VERSION=5.2.0"
 - "RAILS_VERSION=5.1.0"

global_env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_script:
  - jdk_switcher use oraclejdk8
